# Generated by Django 4.0.5 on 2022-07-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountdetails_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='picture',
            field=models.ImageField(default='profile/dummy-image.jpg', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
