# Generated by Django 4.0.5 on 2022-07-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accountdetails_picture_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='ifsc_code',
            field=models.CharField(default='RK012345', max_length=30),
        ),
    ]
