# Generated by Django 4.0.5 on 2022-07-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_useraddress_branch_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='branch_name',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='branch_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch'),
        ),
    ]
