# Generated by Django 4.0.5 on 2022-06-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalotp',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
