# Generated by Django 4.0.5 on 2022-07-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='status',
            field=models.CharField(default='debited', max_length=10),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(default='credited', max_length=10),
        ),
    ]
