# Generated by Django 4.0.5 on 2022-07-25 06:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=50)),
                ('loan_interest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_duration', models.IntegerField(choices=[(1, 'One Year'), (2, 'Two Years'), (3, 'Three Years'), (4, 'Four Years'), (5, 'Five Years')])),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_sanction_status', models.BooleanField(default=False)),
                ('loan_credited_status', models.BooleanField(default=False)),
                ('loan_active_status', models.BooleanField(default=False)),
                ('loan_tenure', models.IntegerField()),
                ('loan_applied_date', models.DateField(default=datetime.date.today)),
                ('rate_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_loan_interest', to='loans.interestrate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
