# Generated by Django 4.0.5 on 2022-07-11 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('HL', 'Home Loan'), ('CL', 'Car Loan'), ('PL', 'Property Loan'), ('EL', 'Education Loan')], max_length=2)),
                ('loan_duration', models.CharField(choices=[('5', 'One Year'), ('2', 'Two Years'), ('5', 'Five Years'), ('10', 'Ten Years')], max_length=10)),
                ('rate_of_interest', models.CharField(choices=[('5', 'One Year'), ('2', 'Two Years'), ('5', 'Five Years'), ('10', 'Ten Years')], max_length=10)),
                ('loan_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
