# Generated by Django 4.0.5 on 2022-07-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetails',
            name='loan_duration',
            field=models.CharField(choices=[('1', 'One Year'), ('2', 'Two Years'), ('5', 'Five Years'), ('10', 'Ten Years')], max_length=10),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='rate_of_interest',
            field=models.CharField(choices=[('5', '5%'), ('6', '6%'), ('7', '7%'), ('8', '8%')], max_length=10),
        ),
    ]
